# Generated by Django 4.0.1 on 2022-04-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_food_order_foodid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delcharge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
