# Generated by Django 4.0.1 on 2022-04-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_delcharge_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='offer',
            field=models.IntegerField(),
        ),
    ]
