# Generated by Django 4.0.1 on 2022-04-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_food_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='offerprice',
            field=models.IntegerField(default=0),
        ),
    ]
