# Generated by Django 4.0.1 on 2022-05-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_order_foodname_remove_order_foodprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offerprice',
            field=models.BigIntegerField(default=0),
        ),
    ]
