# Generated by Django 4.0.1 on 2022-05-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_order_offerprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offerprice',
            field=models.IntegerField(default=0),
        ),
    ]
