# Generated by Django 4.0.1 on 2022-07-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_order_offerprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
